"""Add location to jobs

Revision ID: a8d2f70c21b8
Revises: 7d6c9a0e7622
Create Date: 2026-02-04 01:57:30.679815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d2f70c21b8'
down_revision: Union[str, Sequence[str], None] = '7d6c9a0e7622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'location')
    # ### end Alembic commands ###
